import {defineField} from 'sanity'

export default defineField({
  name: 'seo.home',
  title: 'SEO',
  type: 'object',
  description:
    'Fields to customize how the home page is represented in search results and social media.',
  options: {
    collapsed: false,
    collapsible: true,
  },
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'string',
      description:
        'The SEO title for the home page. Aim for a concise title that includes relevant keywords.',
      validation: (rule) =>
        rule.max(50).warning('Longer titles may be truncated by search engines'),
    }),
    defineField({
      name: 'description',
      title: 'Description',
      type: 'text',
      rows: 2,
      description:
        'A brief description of the home page. This text is often displayed in search engine results.',
      validation: (rule) =>
        rule.max(150).warning('Longer descriptions may be truncated by search engines'),
    }),
    defineField({
      name: 'image',
      title: 'Image',
      type: 'image',
      description:
        'A representative image for the home page, used in search results and social media previews.',
      options: {
        captionField: 'alt',
        hotspot: true,
      },
      fields: [
        {
          name: 'alt',
          type: 'string',
          title: 'Alternative text',
          description:
            'A brief description of the image, important for accessibility and SEO. This will be autogenerated by AI.',
        },
      ],
    }),
  ],
  validation: (rule) => rule.required(),
})
