import {defineField} from 'sanity'

export default defineField({
  name: 'seo.page',
  title: 'SEO',
  type: 'object',
  options: {
    collapsed: false,
    collapsible: true,
  },
  fields: [
    defineField({
      name: 'title',
      title: 'Title',
      type: 'placeholderString',
      description: (
        <>
          The SEO title for the page. If left empty, the document title (<code>title</code>) will be
          used. This title is crucial for search engines and should be carefully crafted.
        </>
      ),
      options: {field: 'title'},
      validation: (rule) =>
        rule.max(50).warning('Longer titles may be truncated by search engines'),
    }),
    defineField({
      name: 'description',
      title: 'Description',
      type: 'text',
      rows: 2,
      description:
        'A short description of the page content. This is often shown in search engine results and should summarize the page effectively.',
      validation: (rule) =>
        rule.max(150).warning('Longer descriptions may be truncated by search engines'),
    }),
    defineField({
      name: 'image',
      title: 'Image',
      type: 'image',
      description:
        'The main image for the page, used in search engine results and social media previews. Choose an image that represents the page content well.',
      options: {
        captionField: 'alt',
        hotspot: true,
      },
      fields: [
        {
          name: 'alt',
          type: 'string',
          title: 'Alternative text',
          description:
            'A brief description of the image, important for accessibility and SEO. This will be autogenerated by AI.',
        },
      ],
    }),
  ],
})
