import {CalendarIcon} from '@sanity/icons'
import {defineField, defineType} from 'sanity'

export const event = defineType({
  type: 'document',
  name: 'event',
  title: 'Event',
  icon: CalendarIcon,
  preview: {
    select: {
      title: 'title',
      subtitle: 'date',
      media: 'image',
    },
  },
  groups: [
    // Group descriptions can clarify the purpose of each group.
    {
      name: 'theme',
      title: 'Theme',
    },
    {
      default: true,
      name: 'editorial',
      title: 'Editorial',
    },
    {
      name: 'seo',
      title: 'SEO',
    },
  ],
  fields: [
    defineField({
      type: 'string',
      name: 'title',
      title: 'Event Title',
      description: 'The main title of the event. This will be displayed prominently.',
    }),
    defineField({
      type: 'slug',
      name: 'slug',
      title: 'Event Slug',
      description: 'The URL-friendly version of the title used for linking.',
      options: {
        source: 'title',
      },
    }),
    defineField({
      name: 'callToAction',
      title: 'Call to action',
      type: 'module.callToAction',
    }),
    defineField({
      type: 'simpleBlockContent',
      name: 'description',
      title: 'Event Description',
      description: 'A detailed description of the event, including its purpose and highlights.',
    }),
    defineField({
      type: 'date',
      name: 'date',
      title: 'Event Date',
      description: 'The specific date when the event is scheduled to occur.',
    }),
    defineField({
      type: 'number',
      name: 'duration',
      title: 'Event Duration',
      description: 'The total duration of the event in minutes.',
      validation: (rule) => [
        rule.required().warning('Remember to set the duration of the event'),
        rule.greaterThan(0).error('Duration has to be above 0'),
      ],
    }),
    defineField({
      type: 'geopoint',
      name: 'location',
      title: 'Event Location',
      description: 'The geographical point where the event will take place.',
    }),
    defineField({
      type: 'image',
      name: 'image',
      title: 'Event Image',
      description: 'A representative image or photograph for the event.',
      options: {
        captionField: 'alt',
      },
      fields: [
        {
          name: 'alt',
          type: 'string',
          title: 'Alternative text',
          description:
            'A brief description of the image, important for accessibility and SEO. This will be autogenerated by AI.',
        },
      ],
    }),
    defineField({
      type: 'number',
      name: 'capacity',
      title: 'Event Capacity',
      description: 'The maximum number of attendees for the event. No value or 0 means unlimited.',
    }),
    defineField({
      type: 'number',
      name: 'price',
      title: 'Event Price ($)',
      description: 'The cost to attend the event. No value or 0 indicates a free event.',
    }),
    defineField({
      name: 'colorTheme',
      title: 'Color Theme',
      type: 'reference',
      description: 'Select a color theme to visually represent the event.',
      to: [{type: 'colorTheme'}],
      group: 'theme',
      initialValue: {
        _type: 'reference',
        _ref: '1a4e28a9-76ae-44a7-92b0-19a07f9b7b79',
      },
    }),
  ],
})
